### ISSUE TITLE
roslaunch openni_launch openni.launch doesn't work & No image in rviz for both hydro and fuerte version 

### ISSUE THREAD

**Issue by LiliMeng** [ros-drivers/rgbd_launch#10]
Hi,

```
I just installed rgbd_launch, and entered $ roslaunch openni_launch openni.launch 
```

in the terminal. Here is the following display.

setting /run_id to fdd70510-d59b-11e3-b2a9-9c4e36a03c1c
process[rosout-1]: started with pid [25454]
started core service [/rosout]
process[camera_nodelet_manager-2]: started with pid [25466]
process[camera/driver-3]: started with pid [25467]
[ INFO] [1399435172.723175739]: Initializing nodelet with 4 worker threads.
process[camera/rgb/debayer-4]: started with pid [25522]
process[camera/rgb/rectify_mono-5]: started with pid [25556]
process[camera/rgb/rectify_color-6]: started with pid [25678]
process[camera/ir/rectify_ir-7]: started with pid [25735]
process[camera/depth/rectify_depth-8]: started with pid [25814]
process[camera/depth/metric_rect-9]: started with pid [25910]
process[camera/depth/metric-10]: started with pid [26000]
process[camera/depth/points-11]: started with pid [26094]
process[camera/register_depth_rgb-12]: started with pid [26118]
process[camera/depth_registered/rectify_depth-13]: started with pid [26150]
[ERROR] [1399435174.010066993]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressedDepth/set_parameters]
[ERROR] [1399435174.016265320]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressed/set_parameters]
process[camera/depth_registered/metric_rect-14]: started with pid [26236]
[ERROR] [1399435174.029595103]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/theora/set_parameters]
process[camera/depth_registered/metric-15]: started with pid [26322]
process[camera/points_xyzrgb_depth_rgb-16]: started with pid [26387]
process[camera/disparity_depth-17]: started with pid [26416]
process[camera/disparity_depth_registered-18]: started with pid [26448]
process[camera_base_link-19]: started with pid [26477]
process[camera_base_link1-20]: started with pid [26493]
[ INFO] [1399435174.820644720]: Number devices connected: 1
[ INFO] [1399435174.820768048]: 1. device on bus 001:10 is a Xbox NUI Camera (2ae) from Microsoft (45e) with serial id 'B00366616417103B'
[ INFO] [1399435174.821742527]: Searching for device with index = 1
process[camera_base_link2-21]: started with pid [26508]
[ INFO] [1399435174.865119388]: Opened 'Xbox NUI Camera' on bus 1:10 with serial number 'B00366616417103B'
[ INFO] [1399435174.884738732]: rgb_frame_id = '/camera_rgb_optical_frame' 
[ INFO] [1399435174.884824412]: depth_frame_id = '/camera_depth_optical_frame' 
[ WARN] [1399435174.888068958]: Camera calibration file /home/lili/.ros/camera_info/rgb_B00366616417103B.yaml not found.
[ WARN] [1399435174.888143330]: Using default parameters for RGB camera calibration.
[ WARN] [1399435174.888205323]: Camera calibration file /home/lili/.ros/camera_info/depth_B00366616417103B.yaml not found.
[ WARN] [1399435174.888254013]: Using default parameters for IR camera calibration.
process[camera_base_link3-22]: started with pid [26672]

When I open rviz, there is no image display.

Could anyone provide some suggestions? Many thanks in advance!

**Comment by mikeferguson** [comment]
Is rviz properly configured? A simpler test might be to run 'rostopic hz camera/blah/blah' where camera/blah/blah is the name of a topic you are expecting to be output.

**Comment by LiliMeng** [comment]
I think maybe there is some conflicts among my many versions of fuerte, groovy, and hydro. Therefore I reinstalled a clean Ubuntu 12.04 and hydro.

When I entered $roslaunch openni_launch openni.launch  this time, it shows that 
[openni.launch] is neither a launch file in package [openni_launch] nor is [openni_launch] a launch file name
But I did $ git clone git clone https://github.com/ros-drivers/rgbd_launch

**Comment by piyushk** [comment]
@LiliMeng I don't think you've installed openni_launch, as it does not install by default. Try installing ros-hydro-openni-launch, which should pull in the system copy of rgbd_launch, and remove your local source copy of rgbd-launch. You should not have to install rgbd-launch from source unless absolutely necessary.

**Comment by LiliMeng** [comment]
@piyushk   Thank you so much! It works now! So the $ros-hydro-openni-launch  has already included the rgbd_launch, is that right?

**Comment by piyushk** [comment]
@LiliMeng Yes. rgbd_launch is also a released package (ros-hydro-rgbd-launch), and openni-launch depends on it, so it was installed automatically.

It should be possible to download rgbd_launch in your catkin workspace which will overwrite the system version, as you were trying to do. Unfortunately, I cannot comment on why it was not working, as there are many things that might have been going wrong.

I'm closing this issue for now, please reopen as necessary.
