### ISSUE TITLE
Release for Jade

### ISSUE THREAD

**Issue by vrabaud** [ros-drivers/rgbd_launch#17]
Thx for releasing that

**Comment by 130s** [comment]
@vrabaud I can take care of this if I have write access to both devel and release repositories.

**Comment by piyushk** [comment]
Thanks! I don't have admin for ros-drivers to add you, but please add yourself to the maintainers as well once you get access (if you'd like to). I don't have a Jade system set up to test this, and probably won't have one for a while.

**Comment by vrabaud** [comment]
done ! thx again @130s (feel free to close the issues too now that you have the rights)

**Comment by 130s** [comment]
Release request is in flight now https://github.com/ros/rosdistro/pull/9823

@vrabaud one last thing; can you activate travis for this repo (maybe at https://travis-ci.org/profile/ros-drivers) ?

**Comment by vrabaud** [comment]
Done ! Not sure who has rights to do so, maybe only admins of the WHOLE organization ? why not.

**Comment by 130s** [comment]
@vrabaud You seem to be in an Owner team. Anyways, can @wjwwood help us to get travis working?

**Comment by vrabaud** [comment]
oh, at @130s, I did enable it, and I guess it's because I am an owner.
