### ISSUE TITLE
Release request 2.1.4

### ISSUE THREAD

**Issue by furushchev** [ros-drivers/rgbd_launch#33]
I think https://github.com/ros-drivers/rgbd_launch/pull/28 is a major update enough to release new version and we need it for CI on other repositories.
Cc: @130s

**Comment by 130s** [comment]
2.1.3 https://github.com/ros/rosdistro/pull/12665 should already include #28 for Indigo. 

For Jade and Kinetic I opened PR #32 where the newly added .test may have caught a regression. Do you want either of those distros?

**Comment by furushchev** [comment]
@130s Oh, I didn't know. At this moment, indigo is enough for us! Thank you!

**Comment by furushchev** [comment]
@130s Sorry, jade is also tested. (at https://github.com/ros-naoqi/pepper_robot/pull/27 )

**Comment by 130s** [comment]
2.2.2 is release requested. Thanks @furushchev for helping this out!
Jade https://github.com/ros/rosdistro/pull/12687
Kinetic https://github.com/ros/rosdistro/pull/12688

**Comment by furushchev** [comment]
@130s Thanks for releasing! :+1:
