### ISSUE TITLE
How to register rgb and depth for gazebo?

### ISSUE THREAD

**Issue by tiberium24** [ros-drivers/rgbd_launch#41]
Hello,
do you know how i can register the two data flows in gazebo?

**Comment by 130s** [comment]
Closing as that sounds general Gazebo question, not specific to `rgbd_launch` package.

You can start with [Googling "Gazebo rgb  depth"](https://www.google.com/search?q=Gazebo+rgb+depth&ie=utf-8&oe=utf-8).
