### ISSUE TITLE
 sudo apt-get install ros-kinetic-rgbd-launch

### ISSUE THREAD

**Issue by linzgood** [ros-drivers/rgbd_launch#43]
~/catkin_ws$    sudo apt-get install ros-kinetic-rgbd-launch

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-kinetic-rgbd-launch

**Comment by 130s** [comment]
That's your `apt` setting issue. [Google suggests that there are bunch of related issues on ros.org](https://www.google.com/search?q=site%3Aros.org+E%3A+Unable+to+locate+package+&ie=utf-8&oe=utf-8), so please consult them.
