### ISSUE TITLE
hydro-upgrade-notice likely not runable on ROS Noetic

### ISSUE THREAD

**Issue by sloretz** [ros-drivers/rgbd_launch#50]
@130s FYI I noticed this while looking at https://github.com/ros/rosdistro/pull/25278

The script `hydro-upgrade-notice` is being installed with a plain CMake `install()`. The shebangs of the installed script will reference `python` which on Focal is Python 2, and is probably not installed.

https://github.com/ros-drivers/rgbd_launch/blob/2420a14c5349d814aea2ed944108fa670ad76a59/CMakeLists.txt#L12-L14

They should actually be installed with `catkin_install_python()` as described on [this ROS wiki page](https://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs).

**Comment by 130s** [comment]
Thanks for the headsup. This line reads to me that this executable, which prints the notification in question, was supposed to be removed during ROS-I.

https://github.com/ros-drivers/rgbd_launch/blob/2420a14c5349d814aea2ed944108fa670ad76a59/scripts/hydro-upgrade-notice#L17

I'm removing it in https://github.com/ros-drivers/rgbd_launch/pull/55.

**Comment by 130s** [comment]
Should be addressed by https://github.com/ros-drivers/rgbd_launch/pull/55
