### ISSUE TITLE
Disparity not published

### ISSUE THREAD

**Issue by awesomebytes** [ros-drivers/rgbd_launch#6]
Hello, I've found out that the disparity is not being published when doing:

roslaunch openni2_launch openni2.launch disparity_processing:=true

Which, in itself, it's calling  disparity.launch.xml from this package.

What I've found out is that https://github.com/ros-drivers/rgbd_launch/blob/hydro-devel/launch/includes/disparity.launch.xml#L17
<remap from="right" to="$(arg projector)" />
projector must be the same as depth in order to get the (synchronized) camera info with the depth image. If not this hangs forever waiting for a synchronized depth img  + camera info.

I got it to publish making the change <arg name="projector" default="projector" /> to <arg name="projector" default="depth" />
(As I see this argument called projector is on other places too).

I'm still testing this, thats why I don't make directly a pull request but I would like to get some feedback from your part.

After getting it to publish I see it publishes data that makes no sense and I get this error:
rosrun image_view disparity_view image:=/camera/depth/disparity
[ERROR] [1395146613.368389631]: Disparity image fields min_disparity and max_disparity are not set

Although in the launcher there is:
    <param name="min_range" value="0.5" />
    <param name="max_range" value="4.0" />

This may have something to do with the file where all this is read:
https://github.com/ros-perception/image_pipeline/blob/hydro-devel/depth_image_proc/src/nodelets/disparity.cpp

**Comment by jordi-pages** [comment]
According to https://github.com/ros-perception/image_pipeline/blob/hydro-devel/depth_image_proc/src/nodelets/disparity.cpp#L136 it seems that the DisparityNodelet is computing the baseline between the projector and the camera prom camera_info->P[3]/fx. Nevertheless, none of the projection matrices P in any of the camera_info topics published includes the baseline. Is the camera_info topic of the projector missing?

**Comment by piyushk** [comment]
I'll try to test it using a kinect and openni_launch/freenect_launch soon. It may be possible that openni2_camera may have a slightly different API from openni_camera causing this issue.

**Comment by piyushk** [comment]
@awesomebytes Apologies for the slow response. I've just tested a kinect using both of these 

```
roslaunch freenect_launch freenect.launch
rosrun image_view disparity_view image:=/camera/depth/disparity
```

and

```
roslaunch openni_launch openni.launch
rosrun image_view disparity_view image:=/camera/depth/disparity
```

The disparity image is coming up fine. I suspect that this is a downstream non-conformance issue with [openni_camera2](https://github.com/ros-drivers/openni2_camera) or (less likely) [openni_launch2](https://github.com/ros-drivers/openni2_launch). Unfortunately, I don't have a sensor to test openni_launch2, but I would be surprised if something is broken within rgbd_launch.

**Comment by awesomebytes** [comment]
Thank you for testing from your part but yeah, it's a problem of openni2 with disparity.launch.xml I'll try to look further into the problem some day... don't know when yet.

**Comment by piyushk** [comment]
I'm closing this thread. Please reopen the issue if an action needs to be taken on rgbd_launch.

**Comment by mintar** [comment]
It's indeed a bug in `openni2_camera`. Both `freenect_camera` and `openni_camera` publish the topic `/camera/projector/camera_info`, but `openni2_camera` doesn't.
