### ISSUE TITLE
Release for Indigo

### ISSUE THREAD

**Issue by mikeferguson** [ros-drivers/rgbd_launch#8]
@piyushk any timeline on an Indigo release? This package is currently blocking openni2_launch.

**Comment by piyushk** [comment]
I don't have a trusty machine right now. I will try and setup a VM sometime later this week to test an Indigo release for this package and the openni/free next drivers.

**Comment by jack-oquin** [comment]
@piyushk: I have released several simple packages to Indigo without having a Trusty development system.

The trick is to use the build farm: add the package to `rosdistro/indigo/distribution.yaml`, then run the pre-release tests using the "devel" option. For a package like this, that is probably sufficient.

**Comment by mikeferguson** [comment]
@piyushk I can't guarantee that everything will build on the farm -- but I have tested openni2_launch (which uses most of rgbd_launch) on Trusty+Indigo, and all was well.

**Comment by piyushk** [comment]
@jack-oquin If I add the entire package to `rosdistro/indigo/distribution.yaml`, won't it try and release the package as well? I assume I've got to set something up slightly differently to make sure that while I can do a pre-release test, the build farm does not try to actually release the package.

**Comment by jack-oquin** [comment]
Yes. Just add the source and doc sections, no release yet.

**Comment by piyushk** [comment]
https://github.com/ros/rosdistro/pull/4132

**Comment by mikeferguson** [comment]
Thanks!
