### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by eggerdo** [ros-drivers/rgbd_launch#9]
Pay attention to the packages that depend on rgbd_launch when changing files here. the last commit requires changing the openni2.launch in openni2_launch because of the now unused machine arg...

**Comment by piyushk** [comment]
The change was made to a new branch called `indigo-devel` that I created yesterday. Are you using it already? If you're working in ROS Hydro, the please use the `hydro-devel` branch. To read more about why the change was made, please refer #5. I did change the default branch to indigo-devel to track indigo bugs correctly.

In any case, thanks for pointing this out. I'll file a downstream bug report with openni2_launch.

**Comment by piyushk** [comment]
https://github.com/ros-drivers/openni2_launch/issues/17

**Comment by eggerdo** [comment]
Ah you're right, I didn't notice that the default branch was set to
indigo-devel, and no I am still working with hydro-devel. Sorry for the
confusion :) I switched back to hydro-devel.
